services:
  - type: web
    name: mind-canvas
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --timeout 90 app:app"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
