services:
  - type: web
    name: mind-canvas
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    # Diubah: Menggunakan worker 'gevent' yang lebih baik untuk menangani
    # permintaan API yang berjalan lama dan mencegah timeout.
    # Ini adalah perbaikan yang paling penting.
    startCommand: "gunicorn --worker-class gevent --workers 1 --timeout 180 app:app"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11